# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a_d1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a_d2 = np.array([[4,5,6],[7,8,9],[10,11,12]])

# Create a 3-dimensional Numpy array using np.array()
a_d3 = np.array([
    [[13,14,15],[16,17,18],[19,20,21]],
    [[22,23,24],[25,26,27],[28,29,30]],
    [[31,32,33],[34,35,36],[37,38,39]]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a_d1.shape, a_d1.ndim, a_d1.dtype, a_d1.size, type(a_d1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a_d2.shape, a_d2.ndim, a_d2.dtype, a_d2.size, type(a_d2)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a_d3.shape, a_d3.ndim, a_d3.dtype, a_d3.size, type(a_d3)

((3, 3, 3), 3, dtype('int32'), 27, numpy.ndarray)

In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
numpy_df = pd.DataFrame(a_d2)
numpy_df

0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [12]:
# Create an array of shape (10, 2) with only ones
d2_one = np.ones((10,2))
d2_one

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
d3_zero = np.full((7,2,3),0)
d3_zero

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10,(7,2))
random_array

array([[7, 1],
       [2, 3],
       [6, 5],
       [8, 7],
       [2, 5],
       [3, 8],
       [3, 2]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomf_array = np.random.rand(3,5)
randomf_array

array([[0.84322332, 0.45350755, 0.19012426, 0.12686704, 0.16350992],
       [0.22099872, 0.32429289, 0.89970565, 0.75297287, 0.24442009],
       [0.3030725 , 0.34921374, 0.71079165, 0.90904325, 0.18250355]])

In [21]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
seeded_array = np.random.randint(0,10,(4,6))
seeded_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_110 = np.random.randint(1,10,(3,7))
print(array_110)
# Find the unique numbers in the array you just created
np.unique(array_110)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [25]:
# Find the 0'th index of the latest array you created
array_110[0]

array([2, 5, 8, 9, 9, 1, 9])

In [31]:
# Get the first 2 rows of latest array you created
array_110[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [34]:
# Get the first 2 values of the first 2 rows of the latest array
array_110[:2,:2]

array([[2, 5],
       [7, 9]])

In [36]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_r = np.random.randint(0,10,(3,5))
array_no = np.ones((3,5))
print(array_r)
print(array_no)

[[0 2 4 2 0]
 [4 9 6 6 8]
 [9 9 2 6 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
# Add the two arrays together
merge_array = array_r + array_no
merge_array

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [38]:
# Create another array of ones of shape (5, 3)
array_ro = np.ones((5,3))
array_ro

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Try add the array of ones and the other most recent array together
array_ro + array_no

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [40]:
# Create another array of ones of shape (3, 5)
array_iro = np.ones((3,5))

In [41]:
# Subtract the new array of ones from the other most recent array
array_no - array_iro

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
# Multiply the ones array with the latest array
array_r * array_no

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [43]:
# Take the latest array to the power of 2 using '**'
array_r ** 2

array([[ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64],
       [81, 81,  4, 36,  0]], dtype=int32)

In [44]:
# Do the same thing with np.square()
np.square(array_r)

array([[ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64],
       [81, 81,  4, 36,  0]], dtype=int32)

In [45]:
# Find the mean of the latest array using np.mean()
array_r.mean()

4.466666666666667

In [46]:
# Find the maximum of the latest array using np.max()
np.max(array_r)

9

In [47]:
# Find the minimum of the latest array using np.min()
np.min(array_r)

0

In [49]:
# Find the standard deviation of the latest array
array_r.std()

3.263263533472111

In [51]:
# Find the variance of the latest array
array_r.var()

10.648888888888889

In [53]:
# Reshape the latest array to (3, 5, 1)
array_r.reshape(3,5,1)

array([[[0],
        [2],
        [4],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [6],
        [8]],

       [[9],
        [9],
        [2],
        [6],
        [0]]])

In [54]:
# Transpose the latest array
array_r.T

array([[0, 4, 9],
       [2, 9, 9],
       [4, 6, 2],
       [2, 6, 6],
       [0, 8, 0]])

What does the transpose do?

In [55]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_square = np.random.randint(0,10,(3,3))
array_notsquare = np.random.randint(0,10,(3,2))
print(array_square)
print(array_notsquare)

[[3 3 4]
 [6 6 3]
 [6 2 5]]
[[1 9]
 [8 4]
 [5 3]]


In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(array_square,array_notsquare)

array([[47, 51],
       [69, 87],
       [47, 77]])

In [58]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_twins1 = np.random.randint(0,10,(4,3))
array_twins2 = np.random.randint(0,10,(4,3))

In [59]:
# Perform a dot product on the two newest arrays you created
np.dot(array_twins1,array_twins2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [60]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_twins1,array_twins2.T)

array([[151,  52, 163, 135],
       [ 30,  24,  54,  42],
       [120,  38, 143, 129],
       [102,  44, 116,  90]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a5 = np.random.randint(0,10,(2,2))
a6 = np.random.randint(0,10,(2,2))

In [62]:
# Compare the two arrays with '>'
a5 > a6

array([[False, False],
       [ True,  True]])

What happens when you compare the arrays with `>`?

In [63]:
# Compare the two arrays with '>='
a5 >= a6

array([[False, False],
       [ True,  True]])

In [64]:
# Find which elements of the first array are greater than 7
a5 > 7

array([[False, False],
       [ True, False]])

In [65]:
# Which parts of each array are equal? (try using '==')
a5 == a6

array([[False, False],
       [False, False]])

In [66]:
# Sort one of the arrays you just created in ascending order
np.sort(a5)

array([[0, 0],
       [3, 9]])

In [67]:
# Sort the indexes of one of the arrays you just created
np.argsort(a5)

array([[0, 1],
       [1, 0]], dtype=int64)

In [69]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a5)

2

In [70]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a5)

0

In [72]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(a5,axis=1)

array([0, 0], dtype=int64)

In [73]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(a5,axis=0)

array([0, 0], dtype=int64)

In [74]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[-0.44176602, -0.08416509,  1.23701607, -1.42647888,  0.33802266],
       [ 1.9745712 ,  1.96503476, -1.93991122, -0.76262696,  0.16865939],
       [-1.32187695, -0.6682467 , -0.137291  ,  1.40132156, -0.04540266]])

In [75]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.